### ISSUE TITLE
Create codepen with project

### ISSUE THREAD

**Issue by Gtes** [fl-05-epam/animation#24]
Create code pen account 
Add credentials to main document
Upload all needed files to codepen
provide link to group chat

**Comment by lyudmyla-horbyk** [comment]
Перенесла проект в codepen https://codepen.io/Lyudmyla/pen/yLYbBgo?editors=1100
Перенесла в свій акаунт, там потрібен був мейл для реєстрації.
Приватний проект можна створити тільки за гроші.
Переходьте за посилання, при потребі можна редагувати.
